import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: "#f9fafb" },
  center: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#f9fafb",
  },
  loadingText: { marginTop: 12, color: "#6b7280", fontSize: 14 },
  cameraContainer: { flex: 1 },
  camera: { flex: 1 },
  cameraOverlay: {
    flex: 1,
    justifyContent: "space-between",
    padding: 24,
    paddingTop: 60,
  },
  cameraTitle: {
    textAlign: "center",
    color: "white",
    fontSize: 18,
    fontWeight: "700",
    backgroundColor: "rgba(0,0,0,0.5)",
    padding: 12,
    borderRadius: 10,
  },
  faceGuide: {
    width: 200,
    height: 200,
    borderWidth: 2,
    borderColor: "white",
    borderRadius: 100,
    alignSelf: "center",
    borderStyle: "dashed",
  },
  cameraButtons: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  btnBatal: {
    backgroundColor: "rgba(0,0,0,0.5)",
    padding: 12,
    borderRadius: 10,
    width: 70,
  },
  btnBatalText: { color: "white", textAlign: "center", fontWeight: "600" },
  btnShutter: {
    width: 70,
    height: 70,
    borderRadius: 35,
    backgroundColor: "white",
    justifyContent: "center",
    alignItems: "center",
  },
  shutterInner: {
    width: 58,
    height: 58,
    borderRadius: 29,
    backgroundColor: "#dc2626",
  },
  lokasiHeader: {
    padding: 16,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    margin: 16,
    borderRadius: 14,
    borderWidth: 1,
  },
  lokasiValid: { backgroundColor: "#f0fdf4", borderColor: "#86efac" },
  lokasiInvalid: { backgroundColor: "#fef2f2", borderColor: "#fca5a5" },
  lokasiHeaderText: { fontSize: 15, fontWeight: "700", color: "#111827" },
  lokasiHeaderSub: { fontSize: 12, color: "#6b7280", marginTop: 2 },
  btnPetaKecil: {
    backgroundColor: "#dc2626",
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  btnPetaKecilText: { color: "white", fontSize: 11, fontWeight: "700" },
  card: {
    backgroundColor: "white",
    marginHorizontal: 16,
    marginBottom: 12,
    borderRadius: 16,
    padding: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 2,
  },
  cardTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: "#111827",
    marginBottom: 16,
  },
  cardLabel: {
    fontSize: 13,
    fontWeight: "600",
    color: "#4b5563",
    marginBottom: 8,
  },
  statusRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#f3f4f6",
  },
  statusLabel: { fontSize: 14, color: "#6b7280" },
  statusValue: {
    fontSize: 14,
    fontWeight: "700",
    color: "#111827",
    flex: 1,
    textAlign: "right",
  },
  badge: { paddingHorizontal: 12, paddingVertical: 4, borderRadius: 999 },
  badgeHadir: { backgroundColor: "#dcfce7" },
  badgeTerlambat: { backgroundColor: "#fef3c7" },
  badgeDefault: { backgroundColor: "#f3f4f6" },
  badgeText: { fontSize: 12, fontWeight: "600" },
  belumAbsen: {
    color: "#9ca3af",
    fontSize: 14,
    textAlign: "center",
    paddingVertical: 12,
  },
  btnCheckin: {
    backgroundColor: "#dc2626",
    borderRadius: 16,
    padding: 24,
    alignItems: "center",
    shadowColor: "#dc2626",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  btnCheckout: {
    backgroundColor: "#0284c7",
    borderRadius: 16,
    padding: 24,
    alignItems: "center",
    shadowColor: "#0284c7",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  btnCheckinText: { color: "white", fontSize: 18, fontWeight: "800" },
  btnCheckinSub: { color: "rgba(255,255,255,0.8)", fontSize: 12, marginTop: 4 },
  selesaiCard: {
    backgroundColor: "#f0fdf4",
    borderRadius: 16,
    padding: 24,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#86efac",
  },
  selesaiText: { fontSize: 18, fontWeight: "800", color: "#15803d" },
  selesaiSub: { fontSize: 14, color: "#6b7280", marginTop: 4 },
  btnVisit: {
    backgroundColor: "#7c3aed",
    borderRadius: 16,
    padding: 20,
    alignItems: "center",
    shadowColor: "#7c3aed",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  btnVisitText: { color: "white", fontSize: 16, fontWeight: "800" },
  btnVisitSub: { color: "rgba(255,255,255,0.8)", fontSize: 12, marginTop: 4 },
  visitItem: { paddingVertical: 12 },
  visitHeader: { flexDirection: "row", alignItems: "flex-start", gap: 12 },
  visitBadge: {
    backgroundColor: "#7c3aed",
    borderRadius: 999,
    width: 28,
    height: 28,
    justifyContent: "center",
    alignItems: "center",
  },
  visitBadgeText: { color: "white", fontSize: 12, fontWeight: "800" },
  visitNama: { fontSize: 14, fontWeight: "700", color: "#111827" },
  visitWaktu: { fontSize: 12, color: "#6b7280", marginTop: 2 },
  visitCatatan: {
    fontSize: 12,
    color: "#9ca3af",
    marginTop: 2,
    fontStyle: "italic",
  },
  btnCheckoutVisit: {
    backgroundColor: "#0284c7",
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  btnCheckoutVisitText: { color: "white", fontSize: 11, fontWeight: "700" },
  divider: { height: 1, backgroundColor: "#f3f4f6", marginTop: 8 },
  sectionTitle: {
    fontSize: 20,
    fontWeight: "800",
    color: "#111827",
    marginBottom: 16,
  },
  previewFoto: {
    width: "100%",
    height: 260,
    borderRadius: 16,
    marginBottom: 16,
  },
  tipePicker: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderWidth: 1.5,
    borderColor: "#e5e7eb",
    borderRadius: 10,
    padding: 14,
    backgroundColor: "#f9fafb",
  },
  tipePickerText: { fontSize: 15, fontWeight: "600", color: "#111827" },
  tipePickerArrow: { color: "#9ca3af", fontSize: 12 },
  inputField: {
    borderWidth: 1.5,
    borderColor: "#e5e7eb",
    borderRadius: 10,
    padding: 14,
    fontSize: 14,
    color: "#111827",
    backgroundColor: "#f9fafb",
  },
  lokasiCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    padding: 16,
    borderRadius: 12,
    marginBottom: 16,
    borderWidth: 1,
  },
  lokasiIcon: { fontSize: 24 },
  lokasiTitle: { fontSize: 14, fontWeight: "700", color: "#111827" },
  lokasiSub: { fontSize: 12, color: "#6b7280", marginTop: 2 },
  btnPeta: {
    backgroundColor: "#dc2626",
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  btnPetaText: { color: "white", fontSize: 12, fontWeight: "700" },
  actionButtons: { gap: 12 },
  btnUlang: {
    borderWidth: 1.5,
    borderColor: "#dc2626",
    borderRadius: 12,
    padding: 14,
    alignItems: "center",
  },
  btnUlangText: { color: "#dc2626", fontSize: 15, fontWeight: "700" },
  btnSubmit: {
    backgroundColor: "#dc2626",
    borderRadius: 12,
    padding: 16,
    alignItems: "center",
  },
  btnSubmitText: { color: "white", fontSize: 16, fontWeight: "700" },
  btnDisabled: { opacity: 0.7 },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "flex-end",
  },
  modalCard: {
    backgroundColor: "white",
    borderRadius: 24,
    padding: 24,
    margin: 16,
    marginBottom: 32,
    gap: 8,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: "#111827",
    marginBottom: 8,
  },
  tipeItem: {
    padding: 16,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: "#e5e7eb",
  },
  tipeItemActive: { backgroundColor: "#dc2626", borderColor: "#dc2626" },
  tipeItemLabel: { fontSize: 15, fontWeight: "700", color: "#111827" },
  tipeItemDesc: { fontSize: 12, color: "#6b7280", marginTop: 2 },
  btnBatalModal: {
    backgroundColor: "#f3f4f6",
    borderRadius: 12,
    padding: 14,
    alignItems: "center",
    marginTop: 4,
  },
  btnBatalModalText: { fontSize: 15, fontWeight: "700", color: "#374151" },
});