import { StyleSheet } from "react-native";

export default StyleSheet.create({
  center: { flex: 1, justifyContent: "center", alignItems: "center" },

  // Tab
  tabBar: {
    flexDirection: "row",
    backgroundColor: "white",
    borderBottomWidth: 1,
    borderBottomColor: "#f3f4f6",
  },
  tabItem: { flex: 1, paddingVertical: 12, alignItems: "center" },
  tabActive: { borderBottomWidth: 2, borderBottomColor: "#dc2626" },
  tabText: { fontSize: 12, color: "#9ca3af", fontWeight: "600" },
  tabTextActive: { color: "#dc2626" },

  // List
  searchRow: { flexDirection: "row", gap: 8, margin: 16, alignItems: "center" },
  searchInput: {
    borderWidth: 1.5,
    borderColor: "#e5e7eb",
    borderRadius: 10,
    padding: 12,
    fontSize: 14,
    backgroundColor: "white",
    color: "#111827",
  },
  btnScanKecil: { backgroundColor: "#dc2626", borderRadius: 10, padding: 12 },
  btnScanKecilText: { color: "white", fontWeight: "700", fontSize: 13 },
  barangCard: {
    backgroundColor: "white",
    borderRadius: 12,
    padding: 16,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 1,
  },
  barangInfo: { flex: 1 },
  barangNama: { fontSize: 15, fontWeight: "700", color: "#111827" },
  barangKode: { fontSize: 12, color: "#9ca3af", marginTop: 2 },
  snBadge: { fontSize: 11, color: "#7c3aed", marginTop: 4 },
  barangStok: { alignItems: "center" },
  stokAngka: { fontSize: 24, fontWeight: "800" },
  stokSatuan: { fontSize: 11, color: "#9ca3af" },
  stokBadge: {
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 999,
    marginTop: 4,
  },
  badgeAman: { backgroundColor: "#dcfce7" },
  badgeMenipis: { backgroundColor: "#fef3c7" },
  badgeHabis: { backgroundColor: "#fee2e2" },
  stokBadgeText: { fontSize: 10, fontWeight: "700" },
  emptyText: { textAlign: "center", color: "#9ca3af", marginTop: 40 },

  // Form
  formTitle: {
    fontSize: 20,
    fontWeight: "800",
    color: "#111827",
    marginBottom: 20,
  },
  label: { fontSize: 13, fontWeight: "600", color: "#4b5563", marginBottom: 8 },
  input: {
    borderWidth: 1.5,
    borderColor: "#e5e7eb",
    borderRadius: 10,
    padding: 14,
    fontSize: 14,
    color: "#111827",
    backgroundColor: "white",
    marginBottom: 16,
  },
  barangChip: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 999,
    borderWidth: 1.5,
    borderColor: "#e5e7eb",
    backgroundColor: "white",
    marginRight: 8,
  },
  barangChipActive: { backgroundColor: "#dc2626", borderColor: "#dc2626" },
  barangChipText: { fontSize: 13, fontWeight: "600", color: "#374151" },
  selectedCard: {
    backgroundColor: "#fef2f2",
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: "#fca5a5",
  },
  selectedNama: { fontSize: 16, fontWeight: "700", color: "#111827" },
  selectedInfo: { fontSize: 13, color: "#6b7280", marginTop: 4 },
  snInfo: { fontSize: 12, color: "#d97706", marginTop: 6 },

  // SN Section
  snSection: {
    backgroundColor: "#f8fafc",
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: "#e2e8f0",
  },
  snHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  btnScanSN: {
    backgroundColor: "#dc2626",
    borderRadius: 8,
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  btnScanSNText: { color: "white", fontWeight: "700", fontSize: 13 },
  snInputRow: { flexDirection: "row", gap: 8, marginBottom: 12 },
  btnTambahSN: {
    backgroundColor: "#374151",
    borderRadius: 10,
    padding: 14,
    justifyContent: "center",
  },
  btnTambahSNText: { color: "white", fontWeight: "700", fontSize: 13 },
  snList: { gap: 6, marginBottom: 12 },
  snItem: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "white",
    borderRadius: 8,
    padding: 10,
    borderWidth: 1,
    borderColor: "#e5e7eb",
  },
  snNomor: {
    fontSize: 12,
    color: "#9ca3af",
    marginRight: 8,
    fontWeight: "700",
  },
  snText: { flex: 1, fontSize: 13, color: "#374151", fontWeight: "600" },
  snHapus: { paddingHorizontal: 8 },
  progressContainer: {
    backgroundColor: "#e5e7eb",
    borderRadius: 999,
    height: 6,
    overflow: "hidden",
    marginBottom: 8,
  },
  progressBar: { height: 6, borderRadius: 999 },
  progressText: {
    fontSize: 12,
    color: "#6b7280",
    textAlign: "center",
    marginTop: 4,
  },

  // Scanner
  scanOverlay: {
    flex: 1,
    justifyContent: "space-between",
    padding: 24,
    paddingTop: 60,
  },
  scanTopBar: { alignItems: "center", gap: 8 },
  scanTitle: {
    color: "white",
    fontSize: 16,
    fontWeight: "700",
    backgroundColor: "rgba(0,0,0,0.6)",
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 10,
    textAlign: "center",
  },
  scanCounter: {
    color: "white",
    fontSize: 13,
    backgroundColor: "#dc2626",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 999,
    fontWeight: "700",
  },
  scanFrame: {
    width: 240,
    height: 240,
    alignSelf: "center",
    position: "relative",
  },
  corner: {
    position: "absolute",
    width: 24,
    height: 24,
    borderColor: "#dc2626",
    borderWidth: 3,
  },
  cornerTL: { top: 0, left: 0, borderRightWidth: 0, borderBottomWidth: 0 },
  cornerTR: { top: 0, right: 0, borderLeftWidth: 0, borderBottomWidth: 0 },
  cornerBL: { bottom: 0, left: 0, borderRightWidth: 0, borderTopWidth: 0 },
  cornerBR: { bottom: 0, right: 0, borderLeftWidth: 0, borderTopWidth: 0 },
  scanHint: {
    color: "white",
    fontSize: 13,
    textAlign: "center",
    backgroundColor: "rgba(0,0,0,0.6)",
    padding: 10,
    borderRadius: 10,
  },
  btnTutupScan: {
    backgroundColor: "white",
    borderRadius: 12,
    padding: 16,
    alignItems: "center",
    marginBottom: 16,
  },
  btnTutupScanText: { color: "#111827", fontSize: 15, fontWeight: "700" },

  // Submit
  btnSubmit: {
    backgroundColor: "#dc2626",
    borderRadius: 12,
    padding: 16,
    alignItems: "center",
    marginTop: 8,
  },
  btnSubmitKeluar: {
    backgroundColor: "#0284c7",
    borderRadius: 12,
    padding: 16,
    alignItems: "center",
    marginTop: 8,
  },
  btnSubmitText: { color: "white", fontSize: 16, fontWeight: "700" },
  btnDisabled: { opacity: 0.7 },

  // Modal hasil scan
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "flex-end",
  },
  modalCard: {
    backgroundColor: "white",
    borderRadius: 24,
    padding: 24,
    margin: 16,
    marginBottom: 32,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: "#111827",
    marginBottom: 16,
  },
  modalItem: { fontSize: 14, color: "#6b7280", marginBottom: 8 },
  modalValue: { fontWeight: "700", color: "#111827" },
  btnTutup: {
    backgroundColor: "#f3f4f6",
    borderRadius: 12,
    padding: 14,
    alignItems: "center",
    marginTop: 16,
  },
  btnTutupText: { fontSize: 15, fontWeight: "700", color: "#374151" },
});