import { StyleSheet } from "react-native";

export default StyleSheet.create({
  center: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingTop: 60,
  },
  tabBar: {
    flexDirection: "row",
    backgroundColor: "white",
    borderBottomWidth: 1,
    borderBottomColor: "#f3f4f6",
  },
  tabItem: { flex: 1, paddingVertical: 14, alignItems: "center" },
  tabActive: { borderBottomWidth: 2, borderBottomColor: "#dc2626" },
  tabText: { fontSize: 13, color: "#9ca3af", fontWeight: "600" },
  tabTextActive: { color: "#dc2626" },

  // Riwayat
  izinCard: {
    backgroundColor: "white",
    borderRadius: 14,
    padding: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 1,
  },
  izinHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 10,
  },
  izinJenis: { fontSize: 15, fontWeight: "700", color: "#111827" },
  statusBadge: { paddingHorizontal: 10, paddingVertical: 4, borderRadius: 999 },
  statusText: { fontSize: 12, fontWeight: "700" },
  izinTanggal: { marginBottom: 6 },
  izinTanggalText: { fontSize: 13, color: "#6b7280" },
  izinAlasan: { fontSize: 13, color: "#374151", lineHeight: 20 },
  attachmentInfo: {
    marginTop: 8,
    backgroundColor: "#f0fdf4",
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 4,
    alignSelf: "flex-start",
  },
  attachmentInfoText: { fontSize: 12, color: "#15803d", fontWeight: "600" },
  catatanReview: {
    marginTop: 10,
    backgroundColor: "#f9fafb",
    borderRadius: 8,
    padding: 10,
    borderLeftWidth: 3,
    borderLeftColor: "#dc2626",
  },
  catatanReviewLabel: {
    fontSize: 11,
    color: "#9ca3af",
    fontWeight: "700",
    marginBottom: 2,
  },
  catatanReviewText: { fontSize: 13, color: "#374151" },
  emptyContainer: { alignItems: "center", paddingTop: 60, gap: 12 },
  emptyIcon: { fontSize: 48 },
  emptyText: { fontSize: 15, color: "#9ca3af", fontWeight: "600" },
  btnAjukanEmpty: {
    backgroundColor: "#dc2626",
    borderRadius: 10,
    paddingHorizontal: 20,
    paddingVertical: 12,
  },
  btnAjukanEmptyText: { color: "white", fontWeight: "700", fontSize: 14 },

  // Form
  formTitle: {
    fontSize: 20,
    fontWeight: "800",
    color: "#111827",
    marginBottom: 20,
  },
  label: { fontSize: 13, fontWeight: "600", color: "#4b5563", marginBottom: 8 },
  input: {
    borderWidth: 1.5,
    borderColor: "#e5e7eb",
    borderRadius: 10,
    padding: 14,
    fontSize: 14,
    color: "#111827",
    backgroundColor: "white",
    marginBottom: 16,
  },
  picker: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderWidth: 1.5,
    borderColor: "#e5e7eb",
    borderRadius: 10,
    padding: 14,
    backgroundColor: "white",
    marginBottom: 16,
  },
  pickerText: { fontSize: 15, fontWeight: "600", color: "#111827" },
  pickerArrow: { color: "#9ca3af", fontSize: 12 },
  durasiCard: {
    backgroundColor: "#eff6ff",
    borderRadius: 10,
    padding: 12,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: "#bfdbfe",
  },
  durasiText: { fontSize: 14, color: "#1d4ed8", fontWeight: "600" },

  // Attachment
  attachSection: { marginBottom: 16 },
  attachHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
  },
  btnTambahFile: {
    backgroundColor: "#dc2626",
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  btnTambahFileText: { color: "white", fontSize: 12, fontWeight: "700" },
  attachPlaceholder: {
    borderWidth: 1.5,
    borderColor: "#e5e7eb",
    borderRadius: 12,
    borderStyle: "dashed",
    padding: 24,
    alignItems: "center",
    backgroundColor: "white",
    gap: 6,
  },
  attachPlaceholderIcon: { fontSize: 32 },
  attachPlaceholderText: { fontSize: 13, color: "#6b7280", fontWeight: "600" },
  attachPlaceholderHint: { fontSize: 12, color: "#dc2626", fontWeight: "600" },
  attachList: { gap: 8 },
  attachItem: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "white",
    borderRadius: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: "#e5e7eb",
    gap: 12,
  },
  attachThumb: {
    width: 52,
    height: 52,
    borderRadius: 8,
    backgroundColor: "#f3f4f6",
  },
  attachPdfThumb: {
    width: 52,
    height: 52,
    borderRadius: 8,
    backgroundColor: "#fee2e2",
    justifyContent: "center",
    alignItems: "center",
  },
  attachPdfIcon: { fontSize: 24 },
  attachItemInfo: { flex: 1, gap: 2 },
  attachItemName: { fontSize: 13, fontWeight: "600", color: "#111827" },
  attachItemSize: { fontSize: 11, color: "#9ca3af" },
  attachItemType: { fontSize: 11, color: "#6b7280" },
  attachRemoveBtn: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: "#fee2e2",
    justifyContent: "center",
    alignItems: "center",
  },
  attachRemoveText: { fontSize: 12, color: "#dc2626", fontWeight: "700" },
  btnTambahLagi: {
    borderWidth: 1.5,
    borderColor: "#dc2626",
    borderRadius: 10,
    padding: 12,
    alignItems: "center",
    borderStyle: "dashed",
  },
  btnTambahLagiText: { color: "#dc2626", fontSize: 13, fontWeight: "700" },

  // Attach Option Modal
  attachOptionBtn: {
    flexDirection: "row",
    alignItems: "center",
    padding: 16,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: "#e5e7eb",
    gap: 14,
  },
  attachOptionIcon: { fontSize: 28 },
  attachOptionLabel: { fontSize: 15, fontWeight: "700", color: "#111827" },
  attachOptionDesc: { fontSize: 12, color: "#6b7280", marginTop: 2 },

  // Info & Submit
  infoBox: {
    backgroundColor: "#f0fdf4",
    borderRadius: 10,
    padding: 14,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: "#86efac",
  },
  infoText: { fontSize: 12, color: "#15803d", lineHeight: 18 },
  btnSubmit: {
    backgroundColor: "#dc2626",
    borderRadius: 12,
    padding: 16,
    alignItems: "center",
    marginBottom: 32,
  },
  btnSubmitText: { color: "white", fontSize: 16, fontWeight: "700" },
  btnDisabled: { opacity: 0.7 },

  // Modal
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "flex-end",
  },
  modalCard: {
    backgroundColor: "white",
    borderRadius: 24,
    padding: 24,
    margin: 16,
    marginBottom: 32,
    gap: 8,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: "#111827",
    marginBottom: 8,
  },
  jenisItem: {
    padding: 16,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: "#e5e7eb",
  },
  jenisItemActive: { backgroundColor: "#dc2626", borderColor: "#dc2626" },
  jenisItemLabel: { fontSize: 15, fontWeight: "700", color: "#111827" },
  jenisItemDesc: { fontSize: 12, color: "#6b7280", marginTop: 2 },
  btnBatalModal: {
    backgroundColor: "#f3f4f6",
    borderRadius: 12,
    padding: 14,
    alignItems: "center",
    marginTop: 4,
  },
  btnBatalModalText: { fontSize: 15, fontWeight: "700", color: "#374151" },
});